
# pubspec.yaml
name: flutter_dart_fullstack
description: A full stack application with Flutter web frontend and Dart backend

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Frontend dependencies
  http: ^0.13.5
  provider: ^6.0.5
  
  # Backend dependencies
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  path: ^1.8.2
  sqlite3: ^2.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7

flutter:
  uses-material-design: true